### ISSUE TITLE
TiP only bug CPU

### ISSUE THREAD

**Issue by renzoredmarth** [AlexanderHarrison/TrainingMode-More#53]
Bug where they will only do tech in place, even tho you set the tech options to something different.
I think it has something to do with setting counter actoin ground/air to none. Might also have something to do with them barely being out of hitstun before getting to the ground but idk for sure 

https://github.com/user-attachments/assets/d8bd6fd3-659b-457d-868a-40333bf40822

**Comment by strabitz** [comment]
so this is happening in your example because if the cpu leaves hitstun, they'll switch from the "tech" state to the "counter" state and then they'll do the counter action, but if the counter action is set to "None", the CPU will shift to the "recovery" state and switch to the game's AI to recover. This AI is probably what's causing the CPU to tech differently from normal. What we can do is have the CPU try to tech in this situation, which would also cause them to not try to recover when off stage, so I'm not sure what behavior we want here. Honestly this makes me think that color overlays would be super helpful, since it'd let you easily visualize when Puff leaves hitstun here. @AlexanderHarrison

**Comment by AlexanderHarrison** [comment]
Fixed by making the cpu wiggle out of tumble when set to "None". No other simple way to fix this.
