### ISSUE TITLE
Infinite Shield on until hit still doesn't work

### ISSUE THREAD

**Issue by CDSSBM** [AlexanderHarrison/TrainingMode-More#81]
In Training Lab when set to these options the shield is supposed to start depleting after getting hit at least once.

**Comment by AlexanderHarrison** [comment]
The way this feature works is a little weird. It does starts depleting, but only until the CPU performs a counter action. So by default, because the CPU immediately counters with grab after being hit on shield, the shield resets to the max size and you never see it deplete. If you increase the "Counter After Frames" or "Counter After Shield Hits" values, or remove the counter action out of shield, you will see the shield deplete before the CPU counters.

What behavior are you expecting? Should the shield to deplete even after the CPU performs an action out of shield? Is the timer to reset when the counter action is none too small? We can discuss how to make how you want to lab possible.

**Comment by CDSSBM** [comment]
I'm pretty sure I misunderstood how it works and just assumed it was bugged, if so then my apologizes.

But basically I thought it was supposed to work the way I explained it in my previous comment. Cpu Stand, infinite shields on until hit, once hit, infinite shield basically turns off and shield acts as normal and starts depleting.

**Comment by AlexanderHarrison** [comment]
Is there something you are trying to lab or practice that can't be achieved with the current options? Then we can figure out a way to add a feature that will help you lab it. I don't want to change the default functionality of infinite shields until hit, because it will mess with other people's methods of labbing shield pressure (myself included).

**Comment by CDSSBM** [comment]
I'm pretty sure I can with the current settings. I was just a bit confused about how it worked. As for adding a new feature, I can't really think of anything. Thank you for responding, though. 

On another note, I'm not sure if this is on my end, but when playing on console on the latest version, turning on input display in Training Lab freezes the game. No error message or anything, the music keeps playing, L+R+A+Start or pressing the Wii reset button does nothing. This can be fully avoided by just not turning it on 😅

**Comment by AlexanderHarrison** [comment]
No worries! Thanks for making an issue! Glad I could clear up how the option worked.

We're aware of the console crashes. I've been pulling my hair out trying to fix it...
